# Generated by Django 4.1 on 2023-05-31 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_client_alter_user_is_mechanic'),
        ('users', '0007_alter_car_owner'),
    ]

    operations = [
    ]
