# Generated by Django 4.1 on 2023-05-31 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_merge_20230531_2343'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
