# Generated by Django 4.1 on 2023-06-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='plate_number',
            field=models.CharField(default='undefined', max_length=255, unique=True),
        ),
    ]
